#!/usr/bin/env bash
# Build, publish, deploy, and verify pi-janus on k3s in one invocation.
#
# The deployment uses Recreate (one replica + one writable credential PVC), so
# this script deliberately waits through the restart before returning. It also:
# - starts from the most recent successful Helm values, not chart defaults;
# - drops values for top-level chart features that no longer exist;
# - server-dry-runs Helm before changing the deployment;
# - builds a vendored baseline x86-64 binary without executing Bun under QEMU;
# - verifies both the binary and image manifest are linux/amd64;
# - pushes an immutable tag and latest, with the deployment pinned immutable;
# - rolls Helm back on deploy failure and rolls back a failed smoke test;
# - verifies /health, /v1/models, and a real pi-agent completion.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JANUS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CHART_DIR="$SCRIPT_DIR"

NAMESPACE="${JANUS_NAMESPACE:-janus-inference-control-plane}"
RELEASE="${JANUS_RELEASE:-janus-inference-control-plane}"
IMAGE_REPOSITORY="${JANUS_IMAGE_REPOSITORY:-}"
TAG_OVERRIDE="${JANUS_IMAGE_TAG:-}"
VALUES_FILE="${JANUS_VALUES_FILE:-}"
DOCKER_BUILDER="${JANUS_DOCKER_BUILDER:-}"
REGISTRY_SCHEME="${JANUS_REGISTRY_SCHEME:-http}"
TIMEOUT="${JANUS_RELEASE_TIMEOUT:-5m}"
SMOKE_PROVIDER="${JANUS_SMOKE_PROVIDER:-janus-k3s}"
SMOKE_MODEL="${JANUS_SMOKE_MODEL:-deepseek/deepseek-v4-flash}"
RUN_TESTS=true
RUN_AGENT_SMOKE=true
PREFLIGHT_ONLY=false

usage() {
	cat <<'EOF'
Usage: chart/k3s-release.sh [options]

Options:
  --namespace NAME       Kubernetes namespace
  --release NAME         Helm release name
  --repository IMAGE     Registry/repository (inferred from live release)
  --tag TAG              Immutable image tag (auto-generated by default)
  --values FILE          Values source (default: latest successful revision)
  --builder NAME         Docker buildx builder (default: selected builder)
  --timeout DURATION     Helm/rollout timeout (default: 5m)
  --smoke-provider NAME  pi provider for end-to-end smoke test (default: janus-k3s)
  --smoke-model ID       Advertised model for smoke test
  --skip-tests           Skip scripts/test.sh
  --skip-agent-smoke     Skip the real pi-agent smoke test
  --preflight-only       Test, build, and Helm dry-run; do not push/deploy
  -h, --help             Show this help

Environment equivalents use the JANUS_* names initialized near the top of the
script, e.g. JANUS_IMAGE_REPOSITORY and JANUS_SMOKE_MODEL.
EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	--namespace) NAMESPACE="$2"; shift 2 ;;
	--release) RELEASE="$2"; shift 2 ;;
	--repository) IMAGE_REPOSITORY="$2"; shift 2 ;;
	--tag) TAG_OVERRIDE="$2"; shift 2 ;;
	--values) VALUES_FILE="$2"; shift 2 ;;
	--builder) DOCKER_BUILDER="$2"; shift 2 ;;
	--timeout) TIMEOUT="$2"; shift 2 ;;
	--smoke-provider) SMOKE_PROVIDER="$2"; shift 2 ;;
	--smoke-model) SMOKE_MODEL="$2"; shift 2 ;;
	--skip-tests) RUN_TESTS=false; shift ;;
	--skip-agent-smoke) RUN_AGENT_SMOKE=false; shift ;;
	--preflight-only) PREFLIGHT_ONLY=true; shift ;;
	-h | --help) usage; exit 0 ;;
	*) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
	esac
done

require_command() {
	command -v "$1" >/dev/null 2>&1 || { echo "required command not found: $1" >&2; exit 1; }
}

for command in bun curl docker file git helm jq kubectl; do
	require_command "$command"
done

sha256_stdin() {
	if command -v shasum >/dev/null 2>&1; then
		shasum -a 256
	else
		sha256sum
	fi
}

content_tag() {
	local revision dirty_hash file
	revision="$(git rev-parse --short HEAD)"
	if [[ -z "$(git status --porcelain --untracked-files=all)" ]]; then
		printf '%s-amd64\n' "$revision"
		return
	fi
	dirty_hash="$({
		git diff --binary HEAD
		git ls-files --others --exclude-standard | LC_ALL=C sort | while IFS= read -r file; do
			printf '\n-- untracked: %s --\n' "$file"
			cat "$file"
		done
	} | sha256_stdin | awk '{print substr($1, 1, 8)}')"
	printf '%s-dirty-%s-amd64\n' "$revision" "$dirty_hash"
}

# Keep only top-level keys that still exist in chart/values.yaml. Current chart
# defaults fill newly-added keys. Removed blocks (such as zcode) cannot leak
# into later Helm revisions or keep obsolete intent alive.
normalize_values() {
	local source="$1"
	local output="$2"
	awk '
		NR == FNR {
			if ($0 ~ /^[A-Za-z0-9_.-]+:/) {
				key = $0
				sub(/:.*/, "", key)
				allowed[key] = 1
			}
			next
		}
		$0 ~ /^[A-Za-z0-9_.-]+:/ {
			key = $0
			sub(/:.*/, "", key)
			keep = allowed[key]
		}
		keep { print }
	' "$CHART_DIR/values.yaml" "$source" > "$output"
}

clean_test_environment() {
	local unset_args=()
	local name
	while IFS='=' read -r name _; do
		case "$name" in
		JANUS_* | PI_JANUS_*) unset_args+=( -u "$name" ) ;;
		esac
	done < <(env)
	env "${unset_args[@]}" "$JANUS_ROOT/scripts/test.sh"
}

WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/janus-k3s-release.XXXXXX")"
cleanup() {
	rm -rf "$WORK_DIR"
}
trap cleanup EXIT

cd "$JANUS_ROOT"
git rev-parse --is-inside-work-tree >/dev/null
kubectl cluster-info >/dev/null
kubectl get namespace "$NAMESPACE" >/dev/null 2>&1 || kubectl create namespace "$NAMESPACE"

SUCCESS_REVISION=""
SUCCESS_VALUES_JSON="$WORK_DIR/success-values.json"
SOURCE_VALUES="$WORK_DIR/source-values.yaml"
if helm history "$RELEASE" -n "$NAMESPACE" -o json > "$WORK_DIR/history.json" 2>/dev/null; then
	SUCCESS_REVISION="$(jq -r '[.[] | select(.status == "deployed" or .status == "superseded")] | max_by(.revision | tonumber) | .revision // empty' "$WORK_DIR/history.json")"
fi

if [[ -n "$VALUES_FILE" ]]; then
	[[ -f "$VALUES_FILE" ]] || { echo "values file not found: $VALUES_FILE" >&2; exit 1; }
	cp "$VALUES_FILE" "$SOURCE_VALUES"
elif [[ -n "$SUCCESS_REVISION" ]]; then
	echo "==> values: preserving successful Helm revision $SUCCESS_REVISION"
	helm get values "$RELEASE" -n "$NAMESPACE" --revision "$SUCCESS_REVISION" -o yaml > "$SOURCE_VALUES"
else
	echo "no successful Helm release; pass --values FILE for the initial install" >&2
	exit 1
fi

if [[ -n "$SUCCESS_REVISION" ]]; then
	helm get values "$RELEASE" -n "$NAMESPACE" --revision "$SUCCESS_REVISION" -o json > "$SUCCESS_VALUES_JSON"
fi

NORMALIZED_VALUES="$WORK_DIR/values.yaml"
normalize_values "$SOURCE_VALUES" "$NORMALIZED_VALUES"
[[ -s "$NORMALIZED_VALUES" ]] || { echo "normalized values are empty" >&2; exit 1; }

mapfile_compat() {
	# Print unique top-level keys; kept as a helper to avoid Bash 4-only mapfile.
	awk '/^[A-Za-z0-9_.-]+:/ { key=$0; sub(/:.*/, "", key); print key }' "$1" | LC_ALL=C sort -u
}
mapfile_compat "$SOURCE_VALUES" > "$WORK_DIR/source-keys"
mapfile_compat "$CHART_DIR/values.yaml" > "$WORK_DIR/chart-keys"
comm -23 "$WORK_DIR/source-keys" "$WORK_DIR/chart-keys" > "$WORK_DIR/dropped-keys" || true
if [[ -s "$WORK_DIR/dropped-keys" ]]; then
	echo "==> values: dropping removed chart keys: $(tr '\n' ' ' < "$WORK_DIR/dropped-keys" | sed 's/ $//')"
fi

if [[ -z "$IMAGE_REPOSITORY" && -s "$SUCCESS_VALUES_JSON" ]]; then
	IMAGE_REPOSITORY="$(jq -r '.image.repository // empty' "$SUCCESS_VALUES_JSON")"
fi
[[ -n "$IMAGE_REPOSITORY" ]] || { echo "image repository is unknown; pass --repository IMAGE" >&2; exit 1; }
[[ "${IMAGE_REPOSITORY##*/}" != *:* ]] || { echo "repository must not include a tag: $IMAGE_REPOSITORY" >&2; exit 1; }

TAG="${TAG_OVERRIDE:-$(content_tag)}"
IMAGE="$IMAGE_REPOSITORY:$TAG"
REGISTRY_HOST="${IMAGE_REPOSITORY%%/*}"
echo "==> release: $IMAGE"

# Catch immutable PVC changes and bad templates before building or restarting.
echo "==> Helm lint + server dry-run"
helm lint "$CHART_DIR" -f "$NORMALIZED_VALUES" \
	--set-string image.repository="$IMAGE_REPOSITORY" \
	--set-string image.tag="$TAG" >/dev/null
helm upgrade --install "$RELEASE" "$CHART_DIR" -n "$NAMESPACE" \
	-f "$NORMALIZED_VALUES" \
	--set-string image.repository="$IMAGE_REPOSITORY" \
	--set-string image.tag="$TAG" \
	--dry-run=server --hide-secret > "$WORK_DIR/helm-dry-run.log"

if [[ "$RUN_TESTS" == true ]]; then
	echo "==> tests"
	clean_test_environment
fi

# Mirror the repository Dockerfile build stage on the host. This preserves the
# mandatory vendor/pi-ai overlay while avoiding Bun under emulated x86 Linux.
echo "==> build vendored linux-x64 binary"
BUILD_ROOT="$WORK_DIR/build"
mkdir -p "$BUILD_ROOT"
cp "$JANUS_ROOT/package.json" "$JANUS_ROOT/bun.lock" "$BUILD_ROOT/"
cp -R "$JANUS_ROOT/src" "$JANUS_ROOT/scripts" "$JANUS_ROOT/vendor" "$BUILD_ROOT/"
(
	cd "$BUILD_ROOT"
	bun install --frozen-lockfile
	if [[ -d vendor/pi-ai/dist ]]; then
		cp -rf vendor/pi-ai/dist/. node_modules/@earendil-works/pi-ai/dist/
		cp vendor/pi-ai/package.json node_modules/@earendil-works/pi-ai/package.json
	fi
	./scripts/build.sh --target linux-x64 --out "$WORK_DIR/out" --skip-deps
)
BINARY="$WORK_DIR/out/pi-janus"
BINARY_TYPE="$(file "$BINARY")"
case "$BINARY_TYPE" in
*"ELF 64-bit"*"x86-64"*) ;;
*) echo "refusing release: expected an x86-64 ELF binary, got: $BINARY_TYPE" >&2; exit 1 ;;
esac

# The runtime-prebuilt Dockerfile target only copies this verified binary. It
# emits an amd64 manifest but never executes x86 Bun under QEMU.
echo "==> package linux/amd64 image"
RUNTIME_CONTEXT="$WORK_DIR/runtime-context"
mkdir -p "$RUNTIME_CONTEXT"
cp "$BINARY" "$RUNTIME_CONTEXT/pi-janus"
BUILDX_ARGS=()
if [[ -n "$DOCKER_BUILDER" ]]; then
	BUILDX_ARGS+=( --builder "$DOCKER_BUILDER" )
fi
docker buildx build "${BUILDX_ARGS[@]}" \
	--platform linux/amd64 \
	--target runtime-prebuilt \
	--load \
	-f "$JANUS_ROOT/Dockerfile" \
	-t "$IMAGE" \
	"$RUNTIME_CONTEXT"
[[ "$(docker image inspect "$IMAGE" --format '{{.Os}}/{{.Architecture}}')" == "linux/amd64" ]] || {
	echo "refusing release: local image is not linux/amd64" >&2
	exit 1
}

if [[ "$PREFLIGHT_ONLY" == true ]]; then
	echo "==> preflight complete (not pushed or deployed): $IMAGE"
	exit 0
fi

curl -fsS --max-time 5 "$REGISTRY_SCHEME://$REGISTRY_HOST/v2/" >/dev/null

echo "==> push immutable image"
docker push "$IMAGE"
docker manifest inspect --insecure -v "$IMAGE" > "$WORK_DIR/manifest.json"
jq -e '
	if type == "array" then
		length > 0 and all(.[]; .Descriptor.platform.os == "linux" and .Descriptor.platform.architecture == "amd64")
	else
		.Descriptor.platform.os == "linux" and .Descriptor.platform.architecture == "amd64"
	end
' "$WORK_DIR/manifest.json" >/dev/null || {
	echo "refusing deploy: remote image manifest is not linux/amd64" >&2
	exit 1
}

echo "==> push latest"
docker tag "$IMAGE" "$IMAGE_REPOSITORY:latest"
docker push "$IMAGE_REPOSITORY:latest"

if kubectl -n "$NAMESPACE" get deploy -l "app.kubernetes.io/instance=$RELEASE" -o json > "$WORK_DIR/old-deploy.json" 2>/dev/null; then
	jq -r '.items[0].spec.template.spec.containers[] | select(.name == "proxy") | .env[]?.name' "$WORK_DIR/old-deploy.json" | LC_ALL=C sort -u > "$WORK_DIR/old-env"
else
	: > "$WORK_DIR/old-env"
fi

HELM_SAFETY=( --cleanup-on-fail --wait --timeout "$TIMEOUT" )
if [[ -n "$SUCCESS_REVISION" ]]; then
	if helm upgrade --help | grep -q -- '--rollback-on-failure'; then
		HELM_SAFETY+=( --rollback-on-failure )
	else
		HELM_SAFETY+=( --atomic )
	fi
fi

echo "==> deploy (pinned immutable tag)"
helm upgrade --install "$RELEASE" "$CHART_DIR" -n "$NAMESPACE" \
	-f "$NORMALIZED_VALUES" \
	--set-string image.repository="$IMAGE_REPOSITORY" \
	--set-string image.tag="$TAG" \
	"${HELM_SAFETY[@]}"

DEPLOYMENT="$(kubectl -n "$NAMESPACE" get deploy -l "app.kubernetes.io/instance=$RELEASE" -o json | jq -r 'if (.items | length) == 1 then .items[0].metadata.name else empty end')"
[[ -n "$DEPLOYMENT" ]] || { echo "expected exactly one deployment for release $RELEASE" >&2; exit 1; }
kubectl -n "$NAMESPACE" rollout status "deployment/$DEPLOYMENT" --timeout="$TIMEOUT"
DEPLOYED_IMAGE="$(kubectl -n "$NAMESPACE" get "deployment/$DEPLOYMENT" -o json | jq -r '.spec.template.spec.containers[] | select(.name == "proxy") | .image')"
[[ "$DEPLOYED_IMAGE" == "$IMAGE" ]] || { echo "deployed image mismatch: $DEPLOYED_IMAGE" >&2; exit 1; }

kubectl -n "$NAMESPACE" get "deployment/$DEPLOYMENT" -o json | jq -r '.spec.template.spec.containers[] | select(.name == "proxy") | .env[]?.name' | LC_ALL=C sort -u > "$WORK_DIR/new-env"
comm -23 "$WORK_DIR/old-env" "$WORK_DIR/new-env" > "$WORK_DIR/removed-env" || true
if [[ -s "$WORK_DIR/removed-env" ]]; then
	echo "==> removed env vars: $(tr '\n' ' ' < "$WORK_DIR/removed-env" | sed 's/ $//')"
fi

SERVICE="$(kubectl -n "$NAMESPACE" get service -l "app.kubernetes.io/instance=$RELEASE" -o json | jq -r 'if (.items | length) == 1 then .items[0].metadata.name else empty end')"
[[ -n "$SERVICE" ]] || { echo "expected exactly one service for release $RELEASE" >&2; exit 1; }
SERVICE_JSON="$WORK_DIR/service.json"
kubectl -n "$NAMESPACE" get "service/$SERVICE" -o json > "$SERVICE_JSON"
SERVICE_HOST="$(jq -r '.status.loadBalancer.ingress[0].ip // .status.loadBalancer.ingress[0].hostname // .spec.clusterIP // empty' "$SERVICE_JSON")"
SERVICE_PORT="$(jq -r '.spec.ports[] | select(.name == "http") | .port' "$SERVICE_JSON")"
[[ -n "$SERVICE_HOST" && -n "$SERVICE_PORT" ]] || { echo "could not determine service endpoint" >&2; exit 1; }
BASE_URL="http://$SERVICE_HOST:$SERVICE_PORT"

verify_release() {
	local values_json="$WORK_DIR/deployed-values.json"
	local secret token_key token models agent_output
	echo "==> health: $BASE_URL/health"
	curl -fsS --retry 20 --retry-delay 2 --retry-all-errors "$BASE_URL/health" | grep -qx 'ok' || return 1

	helm get values "$RELEASE" -n "$NAMESPACE" -o json > "$values_json" || return 1
	secret="$(jq -r '.auth.existingSecret // empty' "$values_json")"
	token_key="$(jq -r '.auth.tokenKey // "token"' "$values_json")"
	CURL_AUTH=()
	if [[ -n "$secret" ]]; then
		token="$(kubectl -n "$NAMESPACE" get secret "$secret" -o "jsonpath={.data.${token_key}}" | base64 --decode)" || return 1
		CURL_AUTH=( -H "Authorization: Bearer $token" )
		export JANUS_TOKEN="$token"
	fi

	models="$(curl -fsS --retry 5 --retry-delay 2 "${CURL_AUTH[@]}" "$BASE_URL/v1/models")" || return 1
	printf '%s' "$models" | jq -e --arg model "$SMOKE_MODEL" '.data | any(.id == $model)' >/dev/null || {
		echo "smoke model is not advertised: $SMOKE_MODEL" >&2
		return 1
	}

	if [[ "$RUN_AGENT_SMOKE" == true ]]; then
		command -v pi >/dev/null 2>&1 || { echo "pi is required for the agent smoke test" >&2; return 1; }
		echo "==> pi-agent smoke: $SMOKE_PROVIDER/$SMOKE_MODEL"
		agent_output="$(pi --provider "$SMOKE_PROVIDER" --model "$SMOKE_MODEL" --print --no-session --no-tools --thinking off 'Reply with exactly: janus k3s release ok' 2> >(tee "$WORK_DIR/pi-smoke.stderr" >&2))" || return 1
		[[ "$agent_output" == "janus k3s release ok" ]] || {
			echo "unexpected pi-agent response: $agent_output" >&2
			return 1
		}
	fi
}

if ! verify_release; then
	echo "release verification failed" >&2
	if [[ -n "$SUCCESS_REVISION" ]]; then
		echo "==> rolling back to successful revision $SUCCESS_REVISION" >&2
		helm rollback "$RELEASE" "$SUCCESS_REVISION" -n "$NAMESPACE" --wait --timeout "$TIMEOUT" || true
	fi
	exit 1
fi

echo "==> release complete: $IMAGE"
